import { onCall, HttpsError } from 'firebase-functions/v2/https';
import { getAuth } from 'firebase-admin/auth';
import { resend } from '../emails/resendClient';
import {
    getEmailVerificationTemplate,
    getEmailVerificationSubject,
} from '../emails/templates/emailVerification';
import { appCheckCallableOptions } from '../config/appCheckOptions';
import { APP_URL } from '../config/urls';

const SENDER_EMAIL = 'DosFilos <onboarding@dosfilos.com>';
const DASHBOARD_URL = `${APP_URL}/dashboard`;
const CONTINUE_URL = `${APP_URL}/auth/verify-email`;

/**
 * Custom email-verification send. Replaces Firebase Auth's default
 * sendEmailVerification (which produces a generic, unbranded email) with
 * one that ships through Resend using our editorial template.
 *
 * The verification LINK is still generated by Firebase Admin SDK
 * (`generateEmailVerificationLink`), so the auth lifecycle is unchanged:
 * user clicks the link → Firebase's hosted handler validates the oobCode →
 * `emailVerified` flips to true on the auth user. We just own the
 * delivery and the look.
 *
 * Authenticated callable: the user must be signed in (just-registered,
 * usually). If the user is already verified we no-op rather than wasting
 * a Resend send.
 *
 * NOTE on signatures: firebase-functions 4.9 has a quirk where the
 * single-arg `onCall<T>(handler)` form (typed handler, no options) can
 * deploy as a Cloud Run service that fails its container health check.
 * We match the pattern used by `onUserLogin` etc — bare `onCall(handler)`
 * with the request shape narrowed inside — which deploys cleanly.
 *
 * NOTE on secrets: this function uses the legacy
 * `functions.config().resend.apikey` pattern (via resendClient.ts) like
 * the rest of our email senders, NOT Secret Manager. If/when we migrate
 * the email stack to Secret Manager, add `{ secrets: ['RESEND_API_KEY'] }`
 * here and to the other senders.
 */
export const sendVerificationEmail = onCall(appCheckCallableOptions(), async (request) => {
        if (!request.auth) {
            throw new HttpsError('unauthenticated', 'Must be signed in to request verification.');
        }

        const uid = request.auth.uid;
        const data = (request.data ?? {}) as { locale?: 'es' | 'en' };
        const locale: 'es' | 'en' = data.locale === 'en' ? 'en' : 'es';

        const userRecord = await getAuth().getUser(uid);
        if (userRecord.emailVerified) {
            return { sent: false, reason: 'already_verified' };
        }
        if (!userRecord.email) {
            throw new HttpsError('failed-precondition', 'User has no email on record.');
        }

        // continueUrl tells Firebase where to send the user after they click
        // the link — our verify-email page picks them up and detects the
        // verified state via auth state listener + reload polling.
        const link = await getAuth().generateEmailVerificationLink(userRecord.email, {
            url: CONTINUE_URL,
            handleCodeInApp: false,
        });

        const name =
            userRecord.displayName ||
            (locale === 'en' ? 'Preacher' : 'Predicador');

        try {
            await resend.emails.send({
                from: SENDER_EMAIL,
                to: userRecord.email,
                subject: getEmailVerificationSubject(locale),
                html: getEmailVerificationTemplate(name, link, DASHBOARD_URL, locale),
            });
            console.log(`[verifyEmail] sent to ${userRecord.email} (${locale})`);
            return { sent: true };
        } catch (err: any) {
            console.error(`[verifyEmail] resend send failed for ${userRecord.email}`, err);
            throw new HttpsError('internal', err?.message ?? 'Email send failed');
        }
    },
);
