import type { SourceType } from '../entities/SourceType';
import type { SourceRecommendation } from './types';

/**
 * Recommendations that don't depend on the paper's passage — lexicons,
 * grammars, theological dictionaries, ancient primary sources, and
 * background works that apply across an entire testament (or both).
 *
 * Indexed by `SourceType`. The helper merges these AFTER the
 * book-specific list, so a Hebrews paper sees Cockerill first
 * (book-specific) then BDAG (invariant).
 *
 * **Testament filtering (v1.7.1):** every invariant entry carries a
 * `testament` flag (`'NT' | 'OT' | 'whole-bible'`). The helper drops
 * cross-testament entries before display so a 2 Peter paper doesn't
 * see HALOT/BDB/Waltke-O'Connor and a Genesis paper doesn't see
 * BDAG/Wallace/TDNT. Without this filter the catalog gave half the
 * users half the catalog as noise.
 *
 * Curation philosophy:
 *   - Cover the works most pastors-with-seminary-training would
 *     actually own or aspire to own.
 *   - 3-5 entries per type (no overload — the rubric only asks for 2-3
 *     citations of any given type usually).
 *   - Mix Spanish editions where they exist (not many in technical tier).
 *   - ISBN where confidently known; null otherwise (don't fabricate).
 */
export const INVARIANT_RECOMMENDATIONS: Partial<Record<SourceType, ReadonlyArray<SourceRecommendation>>> = {
    // ── Greek (NT) lexicons ─────────────────────────────────────────────
    'lexicon-technical': [
        {
            author: 'Bauer, Walter; Danker, Frederick W.; Arndt, William F.; Gingrich, F. Wilbur',
            title: 'A Greek-English Lexicon of the New Testament and Other Early Christian Literature',
            series: 'BDAG',
            publisher: 'University of Chicago Press',
            year: 2000,
            isbn: '9780226039336',
            tier: 'essential',
            languages: ['en'],
            testament: 'NT',
            rationale: 'Estándar absoluto para el griego del NT. Tercera edición (BDAG).',
        },
        {
            author: 'Koehler, Ludwig; Baumgartner, Walter; Stamm, Johann J.',
            title: 'The Hebrew and Aramaic Lexicon of the Old Testament',
            series: 'HALOT',
            publisher: 'Brill',
            year: 1999,
            isbn: '9789004124455',
            tier: 'essential',
            languages: ['en', 'de'],
            testament: 'OT',
            rationale: 'Léxico técnico de referencia para hebreo bíblico y arameo.',
        },
        {
            author: 'Liddell, Henry George; Scott, Robert; Jones, Henry Stuart',
            title: 'A Greek-English Lexicon',
            series: 'LSJ',
            publisher: 'Oxford University Press',
            year: 1996,
            isbn: '9780198642268',
            tier: 'recommended',
            languages: ['en'],
            testament: 'NT',
            rationale: 'Para griego clásico — útil cuando el NT usa palabras con trasfondo helenístico.',
        },
        {
            author: 'Brown, Francis; Driver, S. R.; Briggs, Charles A.',
            title: 'A Hebrew and English Lexicon of the Old Testament',
            series: 'BDB',
            publisher: 'Hendrickson',
            year: 1996,
            isbn: '9781565632066',
            tier: 'standard',
            languages: ['en'],
            testament: 'OT',
            rationale: 'Clásico, en dominio público en versiones digitales. Más accesible que HALOT.',
        },
    ],

    // ── Theological dictionaries ────────────────────────────────────────
    'theological-dictionary': [
        {
            author: 'Kittel, Gerhard; Friedrich, Gerhard (eds.)',
            title: 'Theological Dictionary of the New Testament',
            series: 'TDNT',
            publisher: 'Eerdmans',
            year: 1976,
            isbn: '9780802822437',
            tier: 'essential',
            languages: ['en', 'de'],
            testament: 'NT',
            rationale: '10 vols. Análisis lexicográfico-teológico exhaustivo de cada palabra clave del NT.',
        },
        {
            author: 'Silva, Moisés (ed.)',
            title: 'New International Dictionary of New Testament Theology and Exegesis',
            series: 'NIDNTTE',
            publisher: 'Zondervan Academic',
            year: 2014,
            isbn: '9780310276197',
            tier: 'essential',
            languages: ['en'],
            testament: 'NT',
            rationale: 'Sucesor moderno del NIDNTT de Brown. Más manejable que TDNT.',
        },
        {
            author: 'VanGemeren, Willem A. (ed.)',
            title: 'New International Dictionary of Old Testament Theology and Exegesis',
            series: 'NIDOTTE',
            publisher: 'Zondervan Academic',
            year: 1997,
            isbn: '9780310483700',
            tier: 'essential',
            languages: ['en'],
            testament: 'OT',
            rationale: '5 vols. La contraparte AT del NIDNTTE.',
        },
        {
            author: 'Balz, Horst; Schneider, Gerhard (eds.)',
            title: 'Exegetical Dictionary of the New Testament',
            series: 'EDNT',
            publisher: 'Eerdmans',
            year: 1990,
            isbn: '9780802824158',
            tier: 'recommended',
            languages: ['en', 'de'],
            testament: 'NT',
            rationale: 'Más conciso que TDNT, organizado por palabra griega.',
        },
    ],

    // ── Grammars ────────────────────────────────────────────────────────
    'grammar-syntax': [
        {
            author: 'Wallace, Daniel B.',
            title: 'Greek Grammar Beyond the Basics: An Exegetical Syntax of the New Testament',
            series: null,
            publisher: 'Zondervan Academic',
            year: 1996,
            isbn: '9780310218951',
            tier: 'essential',
            languages: ['en', 'es'],
            testament: 'NT',
            rationale: 'Sintaxis exegética estándar para predicadores y estudiantes. Ed. en español por Vida.',
        },
        {
            author: 'Blass, Friedrich; Debrunner, Albert; Funk, Robert W.',
            title: 'A Greek Grammar of the New Testament and Other Early Christian Literature',
            series: 'BDF',
            publisher: 'University of Chicago Press',
            year: 1961,
            isbn: '9780226271101',
            tier: 'essential',
            languages: ['en', 'de'],
            testament: 'NT',
            rationale: 'Gramática técnica clásica del griego del NT.',
        },
        {
            author: 'Robertson, A. T.',
            title: 'A Grammar of the Greek New Testament in the Light of Historical Research',
            series: null,
            publisher: 'Hodder & Stoughton',
            year: 1934,
            isbn: null,
            tier: 'recommended',
            languages: ['en'],
            testament: 'NT',
            rationale: 'La gramática griega más extensa en inglés. Dominio público en formato digital.',
        },
        {
            author: 'Waltke, Bruce K.; O\'Connor, M.',
            title: 'An Introduction to Biblical Hebrew Syntax',
            series: null,
            publisher: 'Eisenbrauns',
            year: 1990,
            isbn: '9780931464317',
            tier: 'essential',
            languages: ['en'],
            testament: 'OT',
            rationale: 'Sintaxis hebrea bíblica estándar para nivel exegético.',
        },
        {
            author: 'Joüon, Paul; Muraoka, Takamitsu',
            title: 'A Grammar of Biblical Hebrew',
            series: null,
            publisher: 'Pontifical Biblical Institute',
            year: 2006,
            isbn: '9788876536298',
            tier: 'essential',
            languages: ['en'],
            testament: 'OT',
            rationale: 'Gramática hebrea bíblica de referencia técnica. Edición revisada por Muraoka.',
        },
    ],

    // ── Historical / cultural background ────────────────────────────────
    'historical-background': [
        {
            author: 'Keener, Craig S.',
            title: 'The IVP Bible Background Commentary: New Testament',
            series: null,
            publisher: 'IVP Academic',
            year: 2014,
            isbn: '9780830824786',
            tier: 'essential',
            languages: ['en', 'es'],
            testament: 'NT',
            rationale: 'Trasfondo verso por verso del NT. Ed. española por Mundo Hispano (\"Comentario del Contexto Cultural\").',
        },
        {
            author: 'Walton, John H.; Matthews, Victor H.; Chavalas, Mark W.',
            title: 'The IVP Bible Background Commentary: Old Testament',
            series: null,
            publisher: 'IVP Academic',
            year: 2000,
            isbn: '9780830814190',
            tier: 'essential',
            languages: ['en'],
            testament: 'OT',
            rationale: 'Contraparte AT del Keener. Verso por verso, contexto antiguo cercano-oriental.',
        },
        {
            author: 'deSilva, David A.',
            title: 'An Introduction to the New Testament: Contexts, Methods & Ministry Formation',
            series: null,
            publisher: 'IVP Academic',
            year: 2018,
            isbn: '9780830852178',
            tier: 'recommended',
            languages: ['en'],
            testament: 'NT',
            rationale: 'Introducción estándar al NT con énfasis en contexto greco-romano y judío.',
        },
        {
            author: 'Sanders, E. P.',
            title: 'Judaism: Practice and Belief, 63 BCE–66 CE',
            series: null,
            publisher: 'Trinity Press International',
            year: 1992,
            isbn: '9780334024699',
            tier: 'recommended',
            languages: ['en'],
            testament: 'whole-bible',
            rationale: 'Trabajo de referencia sobre judaísmo del Segundo Templo. Útil para AT tardío y NT temprano.',
        },
        {
            author: 'Freedman, David Noel (ed.)',
            title: 'The Anchor Bible Dictionary',
            series: 'ABD',
            publisher: 'Doubleday',
            year: 1992,
            isbn: '9780385193511',
            tier: 'essential',
            languages: ['en'],
            testament: 'whole-bible',
            rationale: '6 vols. Diccionario académico de referencia, transversal a AT/NT.',
        },
    ],

    // ── Primary ancient sources ─────────────────────────────────────────
    'primary-source-ancient': [
        {
            author: 'Josephus, Flavius',
            title: 'The Works of Josephus (Whiston translation)',
            series: null,
            publisher: 'Hendrickson',
            year: 1987,
            isbn: '9780913573860',
            tier: 'essential',
            languages: ['en', 'es'],
            testament: 'whole-bible',
            rationale: 'Antigüedades + Guerra de los Judíos. Esencial para Hechos, NT y trasfondo del AT post-exílico.',
        },
        {
            author: 'Philo of Alexandria',
            title: 'The Works of Philo (Yonge translation)',
            series: null,
            publisher: 'Hendrickson',
            year: 1993,
            isbn: '9780943575933',
            tier: 'recommended',
            languages: ['en'],
            testament: 'whole-bible',
            rationale: 'Filón judío-helenístico. Crítico para Hebreos, Juan, Pablo (lógos, alegoría) + alegorías sobre Pentateuco.',
        },
        {
            author: 'Holmes, Michael W. (ed./trans.)',
            title: 'The Apostolic Fathers: Greek Texts and English Translations',
            series: null,
            publisher: 'Baker Academic',
            year: 2007,
            isbn: '9780801031083',
            tier: 'recommended',
            languages: ['en'],
            testament: 'NT',
            rationale: 'Padres apostólicos (Didaché, Clemente, Ignacio, Bernabé). Diálogo más cercano al NT.',
        },
        {
            author: 'Charlesworth, James H. (ed.)',
            title: 'The Old Testament Pseudepigrapha',
            series: 'OTP',
            publisher: 'Doubleday',
            year: 1983,
            isbn: '9780385188135',
            tier: 'recommended',
            languages: ['en'],
            testament: 'whole-bible',
            rationale: '2 vols. Pseudoepígrafa intertestamentaria — clave para apocalíptica AT (Daniel, Joel) + Judas y Hebreos en el NT.',
        },
    ],

    // ── Critical-text editions ──────────────────────────────────────────
    'biblical-text-edition': [
        {
            author: 'Aland, Barbara; Aland, Kurt; Karavidopoulos, Johannes; Martini, Carlo M.; Metzger, Bruce M. (eds.)',
            title: 'Novum Testamentum Graece',
            series: 'NA28',
            publisher: 'Deutsche Bibelgesellschaft',
            year: 2012,
            isbn: '9783438051592',
            tier: 'essential',
            languages: ['en', 'de'],
            testament: 'NT',
            rationale: 'Texto crítico estándar del NT griego. Edición Nestle-Aland 28.',
        },
        {
            author: 'Schenker, Adrian (ed.)',
            title: 'Biblia Hebraica Quinta',
            series: 'BHQ',
            publisher: 'Deutsche Bibelgesellschaft',
            year: 2004,
            isbn: '9783438052728',
            tier: 'essential',
            languages: ['en', 'de'],
            testament: 'OT',
            rationale: 'Edición crítica del AT hebreo en curso (sucesor de BHS). Cuando un fascículo cubre el libro.',
        },
        {
            author: 'Elliger, Karl; Rudolph, Wilhelm (eds.)',
            title: 'Biblia Hebraica Stuttgartensia',
            series: 'BHS',
            publisher: 'Deutsche Bibelgesellschaft',
            year: 1997,
            isbn: '9783438052193',
            tier: 'recommended',
            languages: ['en', 'de'],
            testament: 'OT',
            rationale: 'Texto crítico AT estándar mientras BHQ se completa. Aparato más compacto.',
        },
        {
            author: 'Rahlfs, Alfred; Hanhart, Robert (eds.)',
            title: 'Septuaginta',
            series: null,
            publisher: 'Deutsche Bibelgesellschaft',
            year: 2006,
            isbn: '9783438051196',
            tier: 'essential',
            languages: ['en', 'de'],
            testament: 'whole-bible',
            rationale: 'Edición Rahlfs-Hanhart de la Septuaginta. Esencial para AT en griego y para citas LXX en el NT.',
        },
    ],

    // ── Critical apparatus (v1.7.1: surfacing the same critical
    //    editions also under this source-type because the rubric's
    //    \"Aparato crítico\" requirement maps here, not to text-edition;
    //    the user reasonably expects NA28 / BHQ to satisfy both) ────
    'critical-apparatus': [
        {
            author: 'Aland, Barbara; Aland, Kurt; Karavidopoulos, Johannes; Martini, Carlo M.; Metzger, Bruce M. (eds.)',
            title: 'Novum Testamentum Graece (aparato crítico)',
            series: 'NA28',
            publisher: 'Deutsche Bibelgesellschaft',
            year: 2012,
            isbn: '9783438051592',
            tier: 'essential',
            languages: ['en', 'de'],
            testament: 'NT',
            rationale: 'Aparato crítico del NA28. Estándar académico para variantes textuales del NT griego.',
        },
        {
            author: 'Aland, Barbara; Aland, Kurt; Karavidopoulos, Johannes; Martini, Carlo M.; Metzger, Bruce M. (eds.)',
            title: 'Editio Critica Maior',
            series: 'ECM',
            publisher: 'Deutsche Bibelgesellschaft',
            year: 2017,
            isbn: null,
            tier: 'essential',
            languages: ['en', 'de'],
            testament: 'NT',
            rationale: 'Aparato crítico exhaustivo (en curso por libro). Más detallado que NA28 cuando el fascículo cubre el libro.',
        },
        {
            author: 'Metzger, Bruce M.',
            title: 'A Textual Commentary on the Greek New Testament',
            series: null,
            publisher: 'Deutsche Bibelgesellschaft',
            year: 1994,
            isbn: '9783438060105',
            tier: 'essential',
            languages: ['en'],
            testament: 'NT',
            rationale: 'Comentario verso a verso sobre las decisiones del comité editorial del NA/UBS. Indispensable para discutir variantes.',
        },
        {
            author: 'Schenker, Adrian (ed.)',
            title: 'Biblia Hebraica Quinta (aparato crítico)',
            series: 'BHQ',
            publisher: 'Deutsche Bibelgesellschaft',
            year: 2004,
            isbn: '9783438052728',
            tier: 'essential',
            languages: ['en', 'de'],
            testament: 'OT',
            rationale: 'Aparato crítico del BHQ. Sucesor del BHS con análisis textual moderno cuando el libro está cubierto.',
        },
        {
            author: 'Elliger, Karl; Rudolph, Wilhelm (eds.)',
            title: 'Biblia Hebraica Stuttgartensia (aparato crítico)',
            series: 'BHS',
            publisher: 'Deutsche Bibelgesellschaft',
            year: 1997,
            isbn: '9783438052193',
            tier: 'recommended',
            languages: ['en', 'de'],
            testament: 'OT',
            rationale: 'Aparato crítico del BHS — aparato más compacto que BHQ pero cubre todo el AT hebreo.',
        },
    ],
};
