import type { SourceType } from '../entities/SourceType';
import type { SourceRecommendation } from './types';

/**
 * Recommendations that don't depend on the paper's passage — lexicons,
 * grammars, theological dictionaries, ancient primary sources, and
 * background works that apply across an entire testament (or both).
 *
 * Indexed by `SourceType`. The helper merges these AFTER the
 * book-specific list, so a Hebrews paper sees Cockerill first
 * (book-specific) then BDAG (invariant).
 *
 * Curation philosophy:
 *   - Cover the works most pastors-with-seminary-training would
 *     actually own or aspire to own.
 *   - 3-5 entries per type (no overload — the rubric only asks for 2-3
 *     citations of any given type usually).
 *   - Mix Spanish editions where they exist (not many in technical tier).
 *   - ISBN where confidently known; null otherwise (don't fabricate).
 */
export const INVARIANT_RECOMMENDATIONS: Partial<Record<SourceType, ReadonlyArray<SourceRecommendation>>> = {
    // ── Greek (NT) lexicons ─────────────────────────────────────────────
    'lexicon-technical': [
        {
            author: 'Bauer, Walter; Danker, Frederick W.; Arndt, William F.; Gingrich, F. Wilbur',
            title: 'A Greek-English Lexicon of the New Testament and Other Early Christian Literature',
            series: 'BDAG',
            publisher: 'University of Chicago Press',
            year: 2000,
            isbn: '9780226039336',
            tier: 'essential',
            languages: ['en'],
            rationale: 'Estándar absoluto para el griego del NT. Tercera edición (BDAG).',
        },
        {
            author: 'Koehler, Ludwig; Baumgartner, Walter; Stamm, Johann J.',
            title: 'The Hebrew and Aramaic Lexicon of the Old Testament',
            series: 'HALOT',
            publisher: 'Brill',
            year: 1999,
            isbn: '9789004124455',
            tier: 'essential',
            languages: ['en', 'de'],
            rationale: 'Léxico técnico de referencia para hebreo bíblico y arameo.',
        },
        {
            author: 'Liddell, Henry George; Scott, Robert; Jones, Henry Stuart',
            title: 'A Greek-English Lexicon',
            series: 'LSJ',
            publisher: 'Oxford University Press',
            year: 1996,
            isbn: '9780198642268',
            tier: 'recommended',
            languages: ['en'],
            rationale: 'Para griego clásico — útil cuando el NT usa palabras con trasfondo helenístico.',
        },
        {
            author: 'Brown, Francis; Driver, S. R.; Briggs, Charles A.',
            title: 'A Hebrew and English Lexicon of the Old Testament',
            series: 'BDB',
            publisher: 'Hendrickson',
            year: 1996,
            isbn: '9781565632066',
            tier: 'standard',
            languages: ['en'],
            rationale: 'Clásico, en dominio público en versiones digitales. Más accesible que HALOT.',
        },
    ],

    // ── Theological dictionaries ────────────────────────────────────────
    'theological-dictionary': [
        {
            author: 'Kittel, Gerhard; Friedrich, Gerhard (eds.)',
            title: 'Theological Dictionary of the New Testament',
            series: 'TDNT',
            publisher: 'Eerdmans',
            year: 1976,
            isbn: '9780802822437',
            tier: 'essential',
            languages: ['en', 'de'],
            rationale: '10 vols. Análisis lexicográfico-teológico exhaustivo de cada palabra clave del NT.',
        },
        {
            author: 'Silva, Moisés (ed.)',
            title: 'New International Dictionary of New Testament Theology and Exegesis',
            series: 'NIDNTTE',
            publisher: 'Zondervan Academic',
            year: 2014,
            isbn: '9780310276197',
            tier: 'essential',
            languages: ['en'],
            rationale: 'Sucesor moderno del NIDNTT de Brown. Más manejable que TDNT.',
        },
        {
            author: 'VanGemeren, Willem A. (ed.)',
            title: 'New International Dictionary of Old Testament Theology and Exegesis',
            series: 'NIDOTTE',
            publisher: 'Zondervan Academic',
            year: 1997,
            isbn: '9780310483700',
            tier: 'essential',
            languages: ['en'],
            rationale: '5 vols. La contraparte AT del NIDNTTE.',
        },
        {
            author: 'Balz, Horst; Schneider, Gerhard (eds.)',
            title: 'Exegetical Dictionary of the New Testament',
            series: 'EDNT',
            publisher: 'Eerdmans',
            year: 1990,
            isbn: '9780802824158',
            tier: 'recommended',
            languages: ['en', 'de'],
            rationale: 'Más conciso que TDNT, organizado por palabra griega.',
        },
    ],

    // ── Grammars ────────────────────────────────────────────────────────
    'grammar-syntax': [
        {
            author: 'Wallace, Daniel B.',
            title: 'Greek Grammar Beyond the Basics: An Exegetical Syntax of the New Testament',
            series: null,
            publisher: 'Zondervan Academic',
            year: 1996,
            isbn: '9780310218951',
            tier: 'essential',
            languages: ['en', 'es'],
            rationale: 'Sintaxis exegética estándar para predicadores y estudiantes. Ed. en español por Vida.',
        },
        {
            author: 'Blass, Friedrich; Debrunner, Albert; Funk, Robert W.',
            title: 'A Greek Grammar of the New Testament and Other Early Christian Literature',
            series: 'BDF',
            publisher: 'University of Chicago Press',
            year: 1961,
            isbn: '9780226271101',
            tier: 'essential',
            languages: ['en', 'de'],
            rationale: 'Gramática técnica clásica del griego del NT.',
        },
        {
            author: 'Robertson, A. T.',
            title: 'A Grammar of the Greek New Testament in the Light of Historical Research',
            series: null,
            publisher: 'Hodder & Stoughton',
            year: 1934,
            isbn: null,
            tier: 'recommended',
            languages: ['en'],
            rationale: 'La gramática griega más extensa en inglés. Dominio público en formato digital.',
        },
        {
            author: 'Waltke, Bruce K.; O\'Connor, M.',
            title: 'An Introduction to Biblical Hebrew Syntax',
            series: null,
            publisher: 'Eisenbrauns',
            year: 1990,
            isbn: '9780931464317',
            tier: 'essential',
            languages: ['en'],
            rationale: 'Sintaxis hebrea bíblica estándar para nivel exegético.',
        },
        {
            author: 'Joüon, Paul; Muraoka, Takamitsu',
            title: 'A Grammar of Biblical Hebrew',
            series: null,
            publisher: 'Pontifical Biblical Institute',
            year: 2006,
            isbn: '9788876536298',
            tier: 'essential',
            languages: ['en'],
            rationale: 'Gramática hebrea bíblica de referencia técnica. Edición revisada por Muraoka.',
        },
    ],

    // ── Historical / cultural background ────────────────────────────────
    'historical-background': [
        {
            author: 'Keener, Craig S.',
            title: 'The IVP Bible Background Commentary: New Testament',
            series: null,
            publisher: 'IVP Academic',
            year: 2014,
            isbn: '9780830824786',
            tier: 'essential',
            languages: ['en', 'es'],
            rationale: 'Trasfondo verso por verso del NT. Ed. española por Mundo Hispano (\"Comentario del Contexto Cultural\").',
        },
        {
            author: 'Walton, John H.; Matthews, Victor H.; Chavalas, Mark W.',
            title: 'The IVP Bible Background Commentary: Old Testament',
            series: null,
            publisher: 'IVP Academic',
            year: 2000,
            isbn: '9780830814190',
            tier: 'essential',
            languages: ['en'],
            rationale: 'Contraparte AT del Keener. Verso por verso, contexto antiguo cercano-oriental.',
        },
        {
            author: 'deSilva, David A.',
            title: 'An Introduction to the New Testament: Contexts, Methods & Ministry Formation',
            series: null,
            publisher: 'IVP Academic',
            year: 2018,
            isbn: '9780830852178',
            tier: 'recommended',
            languages: ['en'],
            rationale: 'Introducción estándar al NT con énfasis en contexto greco-romano y judío.',
        },
        {
            author: 'Sanders, E. P.',
            title: 'Judaism: Practice and Belief, 63 BCE–66 CE',
            series: null,
            publisher: 'Trinity Press International',
            year: 1992,
            isbn: '9780334024699',
            tier: 'recommended',
            languages: ['en'],
            rationale: 'Trabajo de referencia sobre judaísmo del Segundo Templo.',
        },
        {
            author: 'Freedman, David Noel (ed.)',
            title: 'The Anchor Bible Dictionary',
            series: 'ABD',
            publisher: 'Doubleday',
            year: 1992,
            isbn: '9780385193511',
            tier: 'essential',
            languages: ['en'],
            rationale: '6 vols. Diccionario académico de referencia, transversal a AT/NT.',
        },
    ],

    // ── Primary ancient sources ─────────────────────────────────────────
    'primary-source-ancient': [
        {
            author: 'Josephus, Flavius',
            title: 'The Works of Josephus (Whiston translation)',
            series: null,
            publisher: 'Hendrickson',
            year: 1987,
            isbn: '9780913573860',
            tier: 'essential',
            languages: ['en', 'es'],
            rationale: 'Antigüedades + Guerra de los Judíos. Esencial para Hechos y trasfondo del NT.',
        },
        {
            author: 'Philo of Alexandria',
            title: 'The Works of Philo (Yonge translation)',
            series: null,
            publisher: 'Hendrickson',
            year: 1993,
            isbn: '9780943575933',
            tier: 'recommended',
            languages: ['en'],
            rationale: 'Filón judío-helenístico. Crítico para Hebreos, Juan, Pablo (lógos, alegoría).',
        },
        {
            author: 'Holmes, Michael W. (ed./trans.)',
            title: 'The Apostolic Fathers: Greek Texts and English Translations',
            series: null,
            publisher: 'Baker Academic',
            year: 2007,
            isbn: '9780801031083',
            tier: 'recommended',
            languages: ['en'],
            rationale: 'Padres apostólicos (Didaché, Clemente, Ignacio, Bernabé). Diálogo más cercano al NT.',
        },
        {
            author: 'Charlesworth, James H. (ed.)',
            title: 'The Old Testament Pseudepigrapha',
            series: 'OTP',
            publisher: 'Doubleday',
            year: 1983,
            isbn: '9780385188135',
            tier: 'recommended',
            languages: ['en'],
            rationale: '2 vols. Pseudoepígrafa intertestamentaria — clave para apocalíptica, Judas, Hebreos.',
        },
    ],

    // ── Critical-text editions (invariant: same edition for any book) ──
    'biblical-text-edition': [
        {
            author: 'Aland, Barbara; Aland, Kurt; Karavidopoulos, Johannes; Martini, Carlo M.; Metzger, Bruce M. (eds.)',
            title: 'Novum Testamentum Graece',
            series: 'NA28',
            publisher: 'Deutsche Bibelgesellschaft',
            year: 2012,
            isbn: '9783438051592',
            tier: 'essential',
            languages: ['en', 'de'],
            rationale: 'Texto crítico estándar del NT griego. Edición Nestle-Aland 28.',
        },
        {
            author: 'Schenker, Adrian (ed.)',
            title: 'Biblia Hebraica Quinta',
            series: 'BHQ',
            publisher: 'Deutsche Bibelgesellschaft',
            year: 2004,
            isbn: '9783438052728',
            tier: 'essential',
            languages: ['en', 'de'],
            rationale: 'Edición crítica del AT hebreo en curso (sucesor de BHS). Cuando un fascículo cubre el libro.',
        },
        {
            author: 'Elliger, Karl; Rudolph, Wilhelm (eds.)',
            title: 'Biblia Hebraica Stuttgartensia',
            series: 'BHS',
            publisher: 'Deutsche Bibelgesellschaft',
            year: 1997,
            isbn: '9783438052193',
            tier: 'recommended',
            languages: ['en', 'de'],
            rationale: 'Texto crítico AT estándar mientras BHQ se completa. Aparato más compacto.',
        },
        {
            author: 'Rahlfs, Alfred; Hanhart, Robert (eds.)',
            title: 'Septuaginta',
            series: null,
            publisher: 'Deutsche Bibelgesellschaft',
            year: 2006,
            isbn: '9783438051196',
            tier: 'essential',
            languages: ['en', 'de'],
            rationale: 'Edición Rahlfs-Hanhart de la Septuaginta. Esencial para teología bíblica del AT al NT.',
        },
    ],
};
