export interface KeyWord {
    original: string;
    transliteration: string;
    lemma?: string; // Lema/Raíz de la palabra
    literalTranslation?: string; // Traducción literal
    morphology: string;
    syntacticFunction: string;
    significance: string;
}

// RAG source citation
export interface RAGSource {
    title: string;      // Document title
    author?: string;    // Document author if available
    page?: string;      // Page number or section
    usedFor: string;    // Brief description of how it was used
}

export interface ExegeticalStudy {
    passage: string;
    context: {
        historical: string;
        literary: string;
        audience: string;
    };
    keyWords: KeyWord[];
    exegeticalProposition: string;
    pastoralInsights: string[];
    ragSources?: RAGSource[];  // Sources used from library
}

import { HomileticalApproach } from './HomileticalApproach';

export interface HomileticalAnalysis {
    exegeticalStudy: ExegeticalStudy;

    /**
     * 🎯 NEW: Multiple homiletical approaches generated by AI
     * Allows preacher to choose the best direction for their context
     */
    homileticalApproaches?: HomileticalApproach[];

    /**
     * 🎯 NEW: ID of the approach selected by the user
     * Used to determine which approach drives the sermon draft
     */
    selectedApproachId?: string;

    /**
     * 🎯 Computed field: Formatted display text for the selected approach
     * Not stored in DB, computed on the fly for UI display
     */
    approachDisplay?: string;

    /**
     * @deprecated Use homileticalApproaches instead
     * Kept for backward compatibility
     */
    homileticalApproach: 'expository' | 'thematic' | 'narrative' | 'topical';

    contemporaryApplication: string[];
    homileticalProposition: string;
    outlinePreview?: string[]; // 🎯 NEW: Preview of outline points for congregation
    outline: SermonOutline;
    ragSources?: RAGSource[];  // Sources used from library
}

/**
 * Sermon outline structure
 * Extracted as separate type for reusability
 */
export interface SermonOutline {
    mainPoints: {
        title: string;
        description: string;
        scriptureReferences: string[];
    }[];
}


export interface GenerationRules {
    theologicalBias?: string; // e.g., "Reformed", "Charismatic"
    preferredBibleVersion?: string; // e.g., "RV1960", "NVI"
    tone?: 'pastoral' | 'expositivo' | 'narrativo';
    targetAudience?: 'general' | 'youth' | 'children' | 'adults' | 'seniors';
    customInstructions?: string; // User-defined prompt additions
    /**
     * Optional pastoral personalization (situational context,
     * congregation description, illustrations, preacher notes…).
     * When present, the draft prompt prepends a "Voz del Predicador"
     * block so the wizard reaches Faculty parity for occasion-specific
     * sermons.
     */
    personalization?: import('./SermonPersonalization').SermonPersonalization;
    /**
     * Audience rigor tier. Controls how technical the prompt is:
     *   - 'beginner' (default): pastor sin formación teológica formal —
     *     simpler vocabulary, fewer Greek/Hebrew technicalities,
     *     accessible illustrations, less assumed knowledge of systematic
     *     categories.
     *   - 'seminary': pastor con formación seminarista (TMS / reformada
     *     / similar) — deeper morphological + syntactic analysis,
     *     explicit Reformed theological framing where applicable, denser
     *     citations, higher tolerance for technical vocabulary.
     *
     * Affects prompts that build the sermon body (`buildSermonDraftPrompt`).
     * Undefined / 'beginner' = current behavior unchanged.
     */
    audienceRigor?: 'beginner' | 'seminary';
}

export interface SermonContent {
    title: string;
    introduction: string;
    body: {
        point: string;
        content: string;
        scriptureReferences?: string[]; // Referencias cruzadas
        illustration?: string;
        implications?: string[]; // Implicaciones (al menos 2)
        /**
         * Cita de autoridad. OPCIONAL. Null when no verifiable quote
         * exists in the source material. PR #217 hardened the prompt
         * to refuse invention of attributed quotes — when the LLM has
         * no verified source, it returns null and the renderer skips
         * the block. Never accept a fabricated quote here.
         */
        authorityQuote?: string | null;
        transition?: string; // Transición al siguiente punto
    }[];
    conclusion: string;
    callToAction?: string;
    ragSources?: RAGSource[];  // Sources used from library
}

