export interface KeyWord {
    original: string;
    transliteration: string;
    lemma?: string; // Lema/Raíz de la palabra
    literalTranslation?: string; // Traducción literal
    morphology: string;
    syntacticFunction: string;
    significance: string;
}

// RAG source citation
export interface RAGSource {
    title: string;      // Document title
    author?: string;    // Document author if available
    page?: string;      // Page number or section
    usedFor: string;    // Brief description of how it was used
    /**
     * Stable manifest ID assigned at retrieval time (e.g. "S1", "S2"),
     * present on Phase-B and later outputs. The server-side validator
     * uses this to match the entry against the citation manifest the
     * LLM was given — anything without a matching id (or with one not
     * in the manifest) is dropped as a hallucination.
     *
     * Absent on legacy sermons generated before Phase B. Those still
     * render via the bibliography section but don't get inline
     * markers tied to specific prose locations.
     */
    sourceId?: string;
}

/**
 * Persisted snapshot of the citation manifest the server validated
 * against when the sermon was generated. Travels with the sermon
 * (`SermonContent.citationManifest` for drafts, mirrored into the
 * published copy) so the inline-marker renderer can dereference
 * `[N]` back to a real library chunk without re-running retrieval.
 *
 * Phase B v1 caps the manifest to top-K retrieved chunks (typically 10);
 * `excerpt` is truncated to 280 chars to keep the Firestore doc small.
 */
export interface CitationManifest {
    /** Schema version — increments when the manifest shape changes. */
    version: '1';
    entries: CitationManifestEntry[];
}

export interface CitationManifestEntry {
    /** Stable ID the LLM cites with: "S1", "S2", … */
    sourceId: string;
    /** Library resource doc the chunk belongs to. */
    resourceId: string;
    /** Specific chunk within the resource (for back-traceability). */
    chunkId: string;
    /** Snapshot at generation time so the renderer doesn't re-query. */
    title: string;
    author?: string;
    page?: string;
    /**
     * Short excerpt (≤280 chars) from the chunk text — surfaces in the
     * inline-marker popover so the reader can sanity-check that the
     * citation matches what the prose claims.
     */
    excerpt: string;

    // ── Rights-aware fields (ADR-006, PR 0.3) ─────────────────────────
    //
    // Snapshot of the source's rights metadata at generation time. The
    // export pipeline (`aggregateRequiredAttributions`) reads these to
    // decide whether the artefact needs a mandatory attribution footer
    // (e.g. SBLGNT under CC BY 4.0) and to compose it without re-fetching
    // the source doc.

    /** Effective license (e.g. 'Public Domain', 'CC BY 4.0'). */
    license?: string;
    /** Canonical license URL (e.g. https://creativecommons.org/licenses/by/4.0/). */
    licenseUrl?: string;
    /** Verbatim copyright notice line attached by the source publisher. */
    copyright?: string;
    /**
     * Mandatory attribution lines that must appear in the rendered
     * artefact. Aggregated by the export pipeline across all manifest
     * entries; deduplicated so a single SBLGNT attribution renders once
     * per artefact regardless of how many Greek words are cited.
     */
    requiredAttribution?: string[];
}

export interface ExegeticalStudy {
    passage: string;
    context: {
        historical: string;
        literary: string;
        audience: string;
    };
    keyWords: KeyWord[];
    exegeticalProposition: string;
    pastoralInsights: string[];
    ragSources?: RAGSource[];  // Sources used from library
}

import { HomileticalApproach } from './HomileticalApproach';

export interface HomileticalAnalysis {
    exegeticalStudy: ExegeticalStudy;

    /**
     * 🎯 NEW: Multiple homiletical approaches generated by AI
     * Allows preacher to choose the best direction for their context
     */
    homileticalApproaches?: HomileticalApproach[];

    /**
     * 🎯 NEW: ID of the approach selected by the user
     * Used to determine which approach drives the sermon draft
     */
    selectedApproachId?: string;

    /**
     * 🎯 Computed field: Formatted display text for the selected approach
     * Not stored in DB, computed on the fly for UI display
     */
    approachDisplay?: string;

    /**
     * @deprecated Use homileticalApproaches instead
     * Kept for backward compatibility
     */
    homileticalApproach: 'expository' | 'thematic' | 'narrative' | 'topical';

    contemporaryApplication: string[];
    homileticalProposition: string;
    outlinePreview?: string[]; // 🎯 NEW: Preview of outline points for congregation
    outline: SermonOutline;
    ragSources?: RAGSource[];  // Sources used from library
}

/**
 * Sermon outline structure
 * Extracted as separate type for reusability
 */
export interface SermonOutline {
    mainPoints: {
        title: string;
        description: string;
        scriptureReferences: string[];
    }[];
}


export interface GenerationRules {
    theologicalBias?: string; // e.g., "Reformed", "Charismatic"
    preferredBibleVersion?: string; // e.g., "RV1960", "NVI"
    tone?: 'pastoral' | 'expositivo' | 'narrativo';
    targetAudience?: 'general' | 'youth' | 'children' | 'adults' | 'seniors';
    customInstructions?: string; // User-defined prompt additions
    /**
     * Optional pastoral personalization (situational context,
     * congregation description, illustrations, preacher notes…).
     * When present, the draft prompt prepends a "Voz del Predicador"
     * block so the wizard reaches Faculty parity for occasion-specific
     * sermons.
     */
    personalization?: import('./SermonPersonalization').SermonPersonalization;
    /**
     * Audience rigor tier. Controls how technical the prompt is:
     *   - 'beginner' (default): pastor sin formación teológica formal —
     *     simpler vocabulary, fewer Greek/Hebrew technicalities,
     *     accessible illustrations, less assumed knowledge of systematic
     *     categories.
     *   - 'seminary': pastor con formación seminarista (TMS / reformada
     *     / similar) — deeper morphological + syntactic analysis,
     *     explicit Reformed theological framing where applicable, denser
     *     citations, higher tolerance for technical vocabulary.
     *
     * Affects prompts that build the sermon body (`buildSermonDraftPrompt`).
     * Undefined / 'beginner' = current behavior unchanged.
     */
    audienceRigor?: 'beginner' | 'seminary';
    /**
     * Optional provenance context (audit T3 #16 Fase 1). When the
     * sermon was derived from a paper, the caller can pass the source
     * material here so the draft prompt prepends a "Contexto de
     * origen" block. Lets regenerate calls see the same source
     * material the original pre-population saw, instead of collapsing
     * to homiletics+rules alone.
     *
     * Fase 1 ships paperContext only — Faculty and project follow in
     * Fase 2.
     */
    paperContext?: {
        /** Reference of the paper's primary passage. */
        passage: string;
        /** Paper title for grounding the prompt. */
        title?: string;
        /** Full assembled markdown the paper composed (8-15k chars). */
        assembledMarkdown: string;
        /** Optional homiletical brief authored on the paper. */
        assignmentBrief?: string;
    };
    /**
     * Faculty session context (audit T3 #16 Fase 2). When the sermon
     * was derived from a Faculty conversation, the caller can pass the
     * approved outline + the personalization the user attached at the
     * preview-modal step. Lets regenerate preserve the same outline
     * structure + pastoral framing without forcing the user back to
     * Faculty to re-approve.
     *
     * Faculty's full chat transcript is intentionally NOT included —
     * outline + personalization already capture the actionable content,
     * and the transcript would add 10k+ tokens of conversational noise
     * for marginal quality lift.
     */
    facultyContext?: {
        /** Title of the originating Faculty session. */
        sessionTitle: string;
        /** Approved sermon outline. */
        outline: {
            title: string;
            passage: string;
            proposition: string;
            points: { title: string; verses: string }[];
        };
    };
    /**
     * Project context (audit T3 #16 Fase 2). When the sermon belongs
     * to an AIProject with a contextNote, the caller can pass the
     * project's name + note so the draft adapts tone, depth, and
     * applications to the project's congregational reality (already
     * the pattern in Faculty's `ExtractTheologicalContentUseCase`).
     *
     * Applies independently of paperContext / facultyContext — a
     * paper-derived sermon can also belong to a project; both blocks
     * stack in the prompt.
     */
    projectContext?: {
        /** Project name (display only). */
        name: string;
        /** Free-form project description / context note. */
        contextNote: string;
    };
}

export interface SermonContent {
    title: string;
    introduction: string;
    body: {
        point: string;
        content: string;
        scriptureReferences?: string[]; // Referencias cruzadas
        illustration?: string;
        implications?: string[]; // Implicaciones (al menos 2)
        /**
         * Cita de autoridad. OPCIONAL. Null when no verifiable quote
         * exists in the source material. PR #217 hardened the prompt
         * to refuse invention of attributed quotes — when the LLM has
         * no verified source, it returns null and the renderer skips
         * the block. Never accept a fabricated quote here.
         */
        authorityQuote?: string | null;
        transition?: string; // Transición al siguiente punto
    }[];
    conclusion: string;
    callToAction?: string;
    ragSources?: RAGSource[];  // Sources used from library
    /**
     * Phase B: snapshot of the citation manifest the server validated
     * against at generation time. Drives the inline-marker renderer —
     * each `[N]` in the prose dereferences to a `CitationManifestEntry`.
     * Absent on pre-Phase-B sermons (renderer falls back to
     * bibliography-only mode).
     */
    citationManifest?: CitationManifest;
    /**
     * Phase B telemetry: counts of valid vs. dropped citation markers
     * + dropped `ragSources` entries from the post-generation validator
     * pass. Persisted so engineering can audit how often the LLM
     * drifts off the citation contract without re-running generation.
     *
     * `markersDropped > 0` or `droppedEntries.length > 0` means the
     * LLM hallucinated IDs that the server stripped — the user never
     * saw them. Surfaces below 0.5% in production are healthy; spikes
     * suggest prompt regression or a model change worth investigating.
     */
    citationValidation?: CitationValidationStats;
}

/**
 * Telemetry counts emitted by `validateCitations`. Stored on
 * `SermonContent.citationValidation` so the in-app debug surfaces and
 * any downstream analytics pipeline can query them after the fact.
 *
 * Kept here (not in services/) so the persistence layer can import
 * the type without dragging the validator's implementation.
 */
export interface CitationValidationStats {
    markersValid: number;
    markersDropped: number;
    droppedEntries: { reason: 'unknown-id' | 'no-id'; entry: RAGSource }[];
    surfaces: ('introduction' | 'body' | 'conclusion' | 'callToAction')[];
}

