export interface KeyWord {
    original: string;
    transliteration: string;
    lemma?: string; // Lema/Raíz de la palabra
    literalTranslation?: string; // Traducción literal
    morphology: string;
    syntacticFunction: string;
    significance: string;
}

// RAG source citation
export interface RAGSource {
    title: string;      // Document title
    author?: string;    // Document author if available
    page?: string;      // Page number or section
    usedFor: string;    // Brief description of how it was used
}

export interface ExegeticalStudy {
    passage: string;
    context: {
        historical: string;
        literary: string;
        audience: string;
    };
    keyWords: KeyWord[];
    exegeticalProposition: string;
    pastoralInsights: string[];
    ragSources?: RAGSource[];  // Sources used from library
}

import { HomileticalApproach } from './HomileticalApproach';

export interface HomileticalAnalysis {
    exegeticalStudy: ExegeticalStudy;

    /**
     * 🎯 NEW: Multiple homiletical approaches generated by AI
     * Allows preacher to choose the best direction for their context
     */
    homileticalApproaches?: HomileticalApproach[];

    /**
     * 🎯 NEW: ID of the approach selected by the user
     * Used to determine which approach drives the sermon draft
     */
    selectedApproachId?: string;

    /**
     * @deprecated Use homileticalApproaches instead
     * Kept for backward compatibility
     */
    homileticalApproach: 'expository' | 'thematic' | 'narrative' | 'topical';

    contemporaryApplication: string[];
    homileticalProposition: string;
    outlinePreview?: string[]; // 🎯 NEW: Preview of outline points for congregation
    outline: SermonOutline;
    ragSources?: RAGSource[];  // Sources used from library
}

/**
 * Sermon outline structure
 * Extracted as separate type for reusability
 */
export interface SermonOutline {
    mainPoints: {
        title: string;
        description: string;
        scriptureReferences: string[];
    }[];
}


export interface GenerationRules {
    theologicalBias?: string; // e.g., "Reformed", "Charismatic"
    preferredBibleVersion?: string; // e.g., "RV1960", "NVI"
    tone?: 'inspirational' | 'educational' | 'casual' | 'formal' | 'evangelistic';
    targetAudience?: 'general' | 'youth' | 'children' | 'adults' | 'seniors';
    customInstructions?: string; // User-defined prompt additions
}

export interface SermonContent {
    title: string;
    introduction: string;
    body: {
        point: string;
        content: string;
        scriptureReferences?: string[]; // Referencias cruzadas
        illustration?: string;
        implications?: string[]; // Implicaciones (al menos 2)
        authorityQuote?: string; // Cita de autoridad
        transition?: string; // Transición al siguiente punto
    }[];
    conclusion: string;
    callToAction?: string;
    ragSources?: RAGSource[];  // Sources used from library
}

