export type SeriesType = 'manual' | 'thematic' | 'expository';

export type PlannedSermonStatus =
    | 'planned'
    | 'paper-in-progress'
    | 'paper-done'
    | 'sermon-in-progress'
    | 'sermon-done';

// Syntactic unit derived from the pericope assistant. Boundaries follow
// the original-language structure (Greek participial chains, Hebrew
// waw-consecutive blocks, etc.), not chapter/verse divisions.
export interface SyntacticUnit {
    book: string;            // e.g. "2 Pedro"
    chapterStart: number;
    verseStart: number;
    chapterEnd: number;
    verseEnd: number;
    originalLanguage?: 'greek' | 'hebrew';
    justification?: string;  // Generated by the assistant, editable by the user
}

// Represents a planned sermon that hasn't been developed yet
export interface PlannedSermon {
    id: string;           // Unique ID for tracking
    week: number;         // Week number in the series
    title: string;
    description: string;
    passage: string;      // 📌 REQUIRED: Biblical passage (e.g. "Romanos 8:28-39")
    scheduledDate?: Date;
    draftId?: string;     // Links to actual draft once started
    paperId?: string;             // ExegeticalPaper.id derived from this pericope
    syntacticUnit?: SyntacticUnit; // Only present when produced by the pericope assistant
    status?: PlannedSermonStatus;
    /**
     * Expository-assistant enrichment (v1.5+). Captures the
     * homiletical reasoning the wizard produced — the two-level
     * proposition (exegetical + homiletical), the pastoral aim, the
     * special-case treatment, the macro-section the unit belongs to,
     * and the source ExegeticalUnit ids it combines/splits.
     *
     * Optional and additive: planned sermons created by the legacy
     * pericope assistant (v1) or by hand keep `expositoryEnrichment`
     * undefined and behave exactly as before.
     */
    expositoryEnrichment?: PlannedSermonExpositoryEnrichment;
}

/**
 * Surfaces the v1.5 expository-assistant output on the planned sermon
 * so the SeriesDetail page (and downstream paper / Faculty contexts)
 * can show the propositions and pastoral aim without re-querying the
 * assistant run.
 *
 * The fields mirror the `PreachableUnit` shape from
 * `exegesis/expository/PreachableUnit.ts`. We embed the relevant
 * subset here (instead of holding a `preachableUnitId` foreign key)
 * because v1.5 does NOT persist the assistant run server-side — the
 * planned sermon is the only durable record of what the assistant
 * produced.
 */
export interface PlannedSermonExpositoryEnrichment {
    exegeticalProposition: string;
    homileticalProposition: string;
    pastoralObjective: string;
    /** Mirrors `PreachableUnit.caseTreatment`. */
    caseTreatment?: string;
    /** Mirrors `PreachableUnit.sourcedExegeticalUnitIds`. */
    sourcedExegeticalUnitIds?: string[];
    /** Stable id of the macro-section this preachable unit belongs to. */
    macroSectionId?: string;
    /** Notes from the Pase 5 reviewer that the pastor accepted into the persisted plan. */
    fidelityNotes?: string;
}

export interface SeriesMetadata {
    thematic?: {
        topic: string;
        subtopics: string[];
    };
    expository?: {
        book: string;
        chapterRange?: string;
        originalLanguageAnalysis?: any;
        // Pericope assistant run metadata. `version` is the model/prompt
        // signature used to produce the current `plannedSermons[]` units —
        // useful for idempotency and re-run gating. `status` tracks the
        // lifecycle of the assistant invocation itself.
        pericopeAssistantVersion?: string;
        pericopeAssistantStatus?: 'pending' | 'running' | 'reviewed';
    };
    plannedSermons?: PlannedSermon[];  // Sermons planned but not yet developed
    /**
     * Series-level defaults for the exegetical paper of each pericope.
     * Auto-created papers (`SeriesService.autoCreatePapersForPericopes`)
     * snapshot these values at creation time: rubric template is copied
     * into `paper.rubric`; styleGuideId is stored as a live reference;
     * sources are embedded as `ProjectSource[]`. Pastors override any
     * of these per paper after creation — the series defaults stay as
     * the seed, not as a live binding.
     *
     * Optional + additive: pre-existing series have `exegesisDefaults`
     * undefined and behave exactly like before (papers fall back to
     * the user's active rubric / no style guide / empty corpus).
     */
    exegesisDefaults?: SeriesExegesisDefaults;
}

/**
 * Per-source seed used to populate a freshly auto-created paper's
 * `sources[]` array. Stores enough denormalized info (corpusId,
 * displayLabel) so the paper-creation use case doesn't need a fresh
 * LibraryResource lookup per pericope — series-creation already had
 * the data when the pastor picked the source.
 */
export interface SeriesExegesisSourceRef {
    /** LibraryResource id from the user's library — used by the UI
     *  to match against the user's library state and surface
     *  "in your library" affordances. */
    libraryResourceId: string;
    /** Ingestion corpus id. Required by AddProjectSourceInput. */
    corpusId: string;
    /** Human-readable label shown in the paper's corpus list. */
    displayLabel: string;
    /**
     * Editorial source-type classification (commentary-technical,
     * commentary-pastoral, lexicon-greek, etc). Mirrors the
     * `SourceType` enum from the exegesis domain — duplicated as a
     * string here to keep the series entity independent of the
     * exegesis module's internal types.
     */
    sourceType: string;
    /** Inclusion mode passed through to ProjectSource. */
    mode: 'full-document' | 'extracted-excerpts';
}

export interface SeriesExegesisDefaults {
    /**
     * UserRubric template id to apply when creating a pericope's
     * paper. The paper use case COPIES the rubric content into
     * `paper.rubric` (snapshot semantics) and records `rubricTemplateId`
     * on the snapshot for provenance. Pastor can edit the rubric on
     * the paper afterwards without touching the series default.
     *
     * `null` = explicitly opt out of defaults; use the system rubric.
     * `undefined` = no preference set yet (falls back to the user's
     * default rubric, matching today's behaviour).
     */
    rubricTemplateId?: string | null;
    /**
     * UserStyleGuide id. Stored as live reference on the paper, not
     * snapshotted — style guides are formatting rules that benefit
     * from staying up-to-date with the seminary's evolving manual.
     */
    styleGuideId?: string | null;
    /**
     * Initial corpus to seed every auto-created paper with. The
     * Recommendations widget (PR #93) populates these via the
     * "Aplicar set recomendado" CTA, and the pastor can add/remove
     * sources manually from the same card.
     */
    sourceRefs?: SeriesExegesisSourceRef[];
    /**
     * When set, the pastor explicitly applied (or accepted) the
     * recommended corpus set for this series' primary book. Used
     * to skip re-prompting on subsequent visits.
     */
    appliedRecommendationsAt?: Date;
}

export interface SermonSeries {
    id: string;
    userId: string;
    title: string;
    description: string;
    coverUrl?: string | undefined;
    startDate?: Date | undefined;
    endDate?: Date | undefined;
    sermonIds: string[];
    draftIds: string[];  // Sermon IDs that are still in the wizard workflow
    type: SeriesType;
    metadata?: SeriesMetadata | undefined;
    resourceIds: string[];
    createdAt: Date;
    updatedAt: Date;
}

export class SermonSeriesEntity implements SermonSeries {
    constructor(
        public id: string,
        public userId: string,
        public title: string,
        public description: string,
        public sermonIds: string[] = [],
        public draftIds: string[] = [],
        public type: SeriesType = 'manual',
        public resourceIds: string[] = [],
        public startDate?: Date,
        public coverUrl?: string,
        public endDate?: Date,
        public metadata?: SeriesMetadata,
        public createdAt: Date = new Date(),
        public updatedAt: Date = new Date()
    ) {
        this.validate();
    }

    private validate(): void {
        if (!this.title || this.title.trim().length < 3) {
            throw new Error('El título de la serie debe tener al menos 3 caracteres');
        }
        if (!this.userId) {
            throw new Error('La serie debe tener un usuario asociado');
        }
    }

    static create(
        data: Omit<SermonSeries, 'id' | 'createdAt' | 'updatedAt'> & { id?: string }
    ): SermonSeriesEntity {
        return new SermonSeriesEntity(
            data.id ?? crypto.randomUUID(),
            data.userId,
            data.title,
            data.description,
            data.sermonIds ?? [],
            data.draftIds ?? [],
            data.type ?? 'manual',
            data.resourceIds ?? [],
            data.startDate,
            data.coverUrl,
            data.endDate,
            data.metadata,
            new Date(),
            new Date()
        );
    }

    update(data: Partial<Omit<SermonSeries, 'id' | 'userId' | 'createdAt'>>): SermonSeriesEntity {
        return new SermonSeriesEntity(
            this.id,
            this.userId,
            data.title ?? this.title,
            data.description ?? this.description,
            data.sermonIds ?? this.sermonIds,
            data.draftIds ?? this.draftIds,
            data.type ?? this.type,
            data.resourceIds ?? this.resourceIds,
            data.startDate ?? this.startDate,
            data.coverUrl ?? this.coverUrl,
            data.endDate ?? this.endDate,
            data.metadata ?? this.metadata,
            this.createdAt,
            new Date()
        );
    }

    addSermon(sermonId: string): SermonSeriesEntity {
        if (this.sermonIds.includes(sermonId)) {
            return this;
        }
        return this.update({
            sermonIds: [...this.sermonIds, sermonId]
        });
    }

    removeSermon(sermonId: string): SermonSeriesEntity {
        return this.update({
            sermonIds: this.sermonIds.filter(id => id !== sermonId)
        });
    }
}
