import { IGreekTutorService, ISessionRepository, BiblicalPassage, IBibleVersionRepository } from '@dosfilos/domain';

/**
 * Use case: Get biblical passage in multiple versions
 * 
 * SOLID Principles Applied:
 * - Dependency Inversion: Depends on IBibleVersionRepository abstraction
 * - Single Responsibility: Orchestrates passage retrieval only
 * 
 * Architecture Optimization:
 * - Uses LOCAL Bible repository for Spanish/English text (instant, 100% accurate)
 * - Only asks AI for Greek + Transliteration + Tokenization
 * - Reduces AI token usage by ~50%
 * - Faster response times
 */
export class GetPassageTextUseCase {
    constructor(
        private greekTutorService: IGreekTutorService,
        private sessionRepository: ISessionRepository,
        private bibleRepository: IBibleVersionRepository // ← NEW: Injected via DI
    ) { }

    /**
     * Executes the use case with cache-first strategy
     * @param reference Bible reference (e.g., "Romanos 12:1-2" or "Romans 12:1-2")
     * @param fileSearchStoreId Optional Exegesis Library store ID
     * @param language Output language (default: Spanish)
     * @returns BiblicalPassage with all versions and tokenized words
     */
    async execute(
        reference: string,
        fileSearchStoreId?: string,
        language: string = 'Spanish'
    ): Promise<BiblicalPassage> {
        console.log('[GetPassageTextUseCase] Fetching passage:', reference);

        // Phase 3D: Check cache first (global across users)
        const cached = await this.sessionRepository.getCachedPassage(reference);
        if (cached) {
            console.log('[GetPassageTextUseCase] Using cached passage');
            return cached;
        }

        // NEW: Get Bible text from LOCAL repository (not AI!)
        const bibleText = this.bibleRepository.getVerses(reference);
        if (!bibleText) {
            throw new Error(`Invalid Bible reference: ${reference}`);
        }
        console.log('[GetPassageTextUseCase] Retrieved verse from local Bible:', bibleText.substring(0, 50) + '...');

        // Generate ONLY Greek + Transliteration + Tokenization with Gemini
        // Bible text is now passed TO the AI, not generated BY it
        console.log('[GetPassageTextUseCase] Generating Greek analysis with Gemini...');
        try {
            const passage = await this.greekTutorService.getPassageText(
                reference,
                fileSearchStoreId,
                language,
                bibleText // ← NEW: Pass local Bible text to AI
            );

            // Phase 3D: Cache for future use
            await this.sessionRepository.cachePassage(passage);
            console.log('[GetPassageTextUseCase] Successfully cached passage for reuse');

            return passage;
        } catch (error) {
            console.error('[GetPassageTextUseCase] Error fetching passage:', error);
            throw new Error(`Failed to fetch passage ${reference}: ${error instanceof Error ? error.message : 'Unknown error'}`);
        }
    }
}
