/**
 * Catalog of Hebrew Bible books with metadata for navigation.
 *
 * The morphhbKey must match exactly the filename in the morphhb WLC directory
 * (e.g. "Jonah" → https://raw.githubusercontent.com/.../wlc/Jonah.xml).
 *
 * Chapter counts are from the standard MT canon.
 */

import type { HebrewBook } from '@dosfilos/domain';
import { BibleSection } from '@dosfilos/domain';

export const HEBREW_BOOKS_CATALOG: HebrewBook[] = [
  // ── Torah (Pentateuco) ────────────────────────────────────────────────────
  {
    morphhbKey: 'Gen',
    abbreviation: 'Gén',
    nameSpanish: 'Génesis',
    nameEnglish: 'Genesis',
    nameHebrew: 'בְּרֵאשִׁית',
    section: BibleSection.TORAH,
    chapterCount: 50,
    canonicalOrder: 1,
  },
  {
    morphhbKey: 'Exod',
    abbreviation: 'Éx',
    nameSpanish: 'Éxodo',
    nameEnglish: 'Exodus',
    nameHebrew: 'שְׁמוֹת',
    section: BibleSection.TORAH,
    chapterCount: 40,
    canonicalOrder: 2,
  },
  {
    morphhbKey: 'Lev',
    abbreviation: 'Lev',
    nameSpanish: 'Levítico',
    nameEnglish: 'Leviticus',
    nameHebrew: 'וַיִּקְרָא',
    section: BibleSection.TORAH,
    chapterCount: 27,
    canonicalOrder: 3,
  },
  {
    morphhbKey: 'Num',
    abbreviation: 'Núm',
    nameSpanish: 'Números',
    nameEnglish: 'Numbers',
    nameHebrew: 'בְּמִדְבַּר',
    section: BibleSection.TORAH,
    chapterCount: 36,
    canonicalOrder: 4,
  },
  {
    morphhbKey: 'Deut',
    abbreviation: 'Dt',
    nameSpanish: 'Deuteronomio',
    nameEnglish: 'Deuteronomy',
    nameHebrew: 'דְּבָרִים',
    section: BibleSection.TORAH,
    chapterCount: 34,
    canonicalOrder: 5,
  },

  // ── Profetas Anteriores (Nevi'im Rishonim) ───────────────────────────────
  {
    morphhbKey: 'Josh',
    abbreviation: 'Jos',
    nameSpanish: 'Josué',
    nameEnglish: 'Joshua',
    nameHebrew: 'יְהוֹשֻׁעַ',
    section: BibleSection.FORMER_PROPHETS,
    chapterCount: 24,
    canonicalOrder: 6,
  },
  {
    morphhbKey: 'Judg',
    abbreviation: 'Jue',
    nameSpanish: 'Jueces',
    nameEnglish: 'Judges',
    nameHebrew: 'שׁוֹפְטִים',
    section: BibleSection.FORMER_PROPHETS,
    chapterCount: 21,
    canonicalOrder: 7,
  },
  {
    morphhbKey: '1Sam',
    abbreviation: '1Sam',
    nameSpanish: '1 Samuel',
    nameEnglish: '1 Samuel',
    nameHebrew: 'שְׁמוּאֵל א',
    section: BibleSection.FORMER_PROPHETS,
    chapterCount: 31,
    canonicalOrder: 8,
  },
  {
    morphhbKey: '2Sam',
    abbreviation: '2Sam',
    nameSpanish: '2 Samuel',
    nameEnglish: '2 Samuel',
    nameHebrew: 'שְׁמוּאֵל ב',
    section: BibleSection.FORMER_PROPHETS,
    chapterCount: 24,
    canonicalOrder: 9,
  },
  {
    morphhbKey: '1Kgs',
    abbreviation: '1Re',
    nameSpanish: '1 Reyes',
    nameEnglish: '1 Kings',
    nameHebrew: 'מְלָכִים א',
    section: BibleSection.FORMER_PROPHETS,
    chapterCount: 22,
    canonicalOrder: 10,
  },
  {
    morphhbKey: '2Kgs',
    abbreviation: '2Re',
    nameSpanish: '2 Reyes',
    nameEnglish: '2 Kings',
    nameHebrew: 'מְלָכִים ב',
    section: BibleSection.FORMER_PROPHETS,
    chapterCount: 25,
    canonicalOrder: 11,
  },

  // ── Profetas Posteriores (Nevi'im Aharonim) ──────────────────────────────
  {
    morphhbKey: 'Isa',
    abbreviation: 'Is',
    nameSpanish: 'Isaías',
    nameEnglish: 'Isaiah',
    nameHebrew: 'יְשַׁעְיָהוּ',
    section: BibleSection.LATTER_PROPHETS,
    chapterCount: 66,
    canonicalOrder: 12,
  },
  {
    morphhbKey: 'Jer',
    abbreviation: 'Jer',
    nameSpanish: 'Jeremías',
    nameEnglish: 'Jeremiah',
    nameHebrew: 'יִרְמְיָהוּ',
    section: BibleSection.LATTER_PROPHETS,
    chapterCount: 52,
    canonicalOrder: 13,
  },
  {
    morphhbKey: 'Ezek',
    abbreviation: 'Ez',
    nameSpanish: 'Ezequiel',
    nameEnglish: 'Ezekiel',
    nameHebrew: 'יְחֶזְקֵאל',
    section: BibleSection.LATTER_PROPHETS,
    chapterCount: 48,
    canonicalOrder: 14,
  },
  {
    morphhbKey: 'Hos',
    abbreviation: 'Os',
    nameSpanish: 'Oseas',
    nameEnglish: 'Hosea',
    nameHebrew: 'הוֹשֵׁעַ',
    section: BibleSection.LATTER_PROPHETS,
    chapterCount: 14,
    canonicalOrder: 15,
  },
  {
    morphhbKey: 'Amos',
    abbreviation: 'Am',
    nameSpanish: 'Amós',
    nameEnglish: 'Amos',
    nameHebrew: 'עָמוֹס',
    section: BibleSection.LATTER_PROPHETS,
    chapterCount: 9,
    canonicalOrder: 16,
  },
  {
    morphhbKey: 'Jonah',
    abbreviation: 'Jon',
    nameSpanish: 'Jonás',
    nameEnglish: 'Jonah',
    nameHebrew: 'יוֹנָה',
    section: BibleSection.LATTER_PROPHETS,
    chapterCount: 4,
    canonicalOrder: 17,
  },
  {
    morphhbKey: 'Mic',
    abbreviation: 'Mi',
    nameSpanish: 'Miqueas',
    nameEnglish: 'Micah',
    nameHebrew: 'מִיכָה',
    section: BibleSection.LATTER_PROPHETS,
    chapterCount: 7,
    canonicalOrder: 18,
  },
  {
    morphhbKey: 'Nah',
    abbreviation: 'Nah',
    nameSpanish: 'Nahúm',
    nameEnglish: 'Nahum',
    nameHebrew: 'נַחוּם',
    section: BibleSection.LATTER_PROPHETS,
    chapterCount: 3,
    canonicalOrder: 19,
  },
  {
    morphhbKey: 'Hab',
    abbreviation: 'Hab',
    nameSpanish: 'Habacuc',
    nameEnglish: 'Habakkuk',
    nameHebrew: 'חֲבַקּוּק',
    section: BibleSection.LATTER_PROPHETS,
    chapterCount: 3,
    canonicalOrder: 20,
  },
  {
    morphhbKey: 'Zeph',
    abbreviation: 'Sof',
    nameSpanish: 'Sofonías',
    nameEnglish: 'Zephaniah',
    nameHebrew: 'צְפַנְיָה',
    section: BibleSection.LATTER_PROPHETS,
    chapterCount: 3,
    canonicalOrder: 21,
  },
  {
    morphhbKey: 'Hag',
    abbreviation: 'Hag',
    nameSpanish: 'Hageo',
    nameEnglish: 'Haggai',
    nameHebrew: 'חַגַּי',
    section: BibleSection.LATTER_PROPHETS,
    chapterCount: 2,
    canonicalOrder: 22,
  },
  {
    morphhbKey: 'Zech',
    abbreviation: 'Zac',
    nameSpanish: 'Zacarías',
    nameEnglish: 'Zechariah',
    nameHebrew: 'זְכַרְיָה',
    section: BibleSection.LATTER_PROPHETS,
    chapterCount: 14,
    canonicalOrder: 23,
  },
  {
    morphhbKey: 'Mal',
    abbreviation: 'Mal',
    nameSpanish: 'Malaquías',
    nameEnglish: 'Malachi',
    nameHebrew: 'מַלְאָכִי',
    section: BibleSection.LATTER_PROPHETS,
    chapterCount: 4,
    canonicalOrder: 24,
  },

  // ── Escritos (Ketuvim) ────────────────────────────────────────────────────
  {
    morphhbKey: 'Ps',
    abbreviation: 'Sal',
    nameSpanish: 'Salmos',
    nameEnglish: 'Psalms',
    nameHebrew: 'תְּהִלִּים',
    section: BibleSection.WRITINGS,
    chapterCount: 150,
    canonicalOrder: 25,
  },
  {
    morphhbKey: 'Job',
    abbreviation: 'Job',
    nameSpanish: 'Job',
    nameEnglish: 'Job',
    nameHebrew: 'אִיּוֹב',
    section: BibleSection.WRITINGS,
    chapterCount: 42,
    canonicalOrder: 26,
  },
  {
    morphhbKey: 'Prov',
    abbreviation: 'Prov',
    nameSpanish: 'Proverbios',
    nameEnglish: 'Proverbs',
    nameHebrew: 'מִשְׁלֵי',
    section: BibleSection.WRITINGS,
    chapterCount: 31,
    canonicalOrder: 27,
  },
  {
    morphhbKey: 'Ruth',
    abbreviation: 'Rt',
    nameSpanish: 'Rut',
    nameEnglish: 'Ruth',
    nameHebrew: 'רוּת',
    section: BibleSection.WRITINGS,
    chapterCount: 4,
    canonicalOrder: 28,
  },
  {
    morphhbKey: 'Cant',
    abbreviation: 'Cnt',
    nameSpanish: 'Cantares',
    nameEnglish: 'Song of Songs',
    nameHebrew: 'שִׁיר הַשִּׁירִים',
    section: BibleSection.WRITINGS,
    chapterCount: 8,
    canonicalOrder: 29,
  },
  {
    morphhbKey: 'Eccl',
    abbreviation: 'Ecl',
    nameSpanish: 'Eclesiastés',
    nameEnglish: 'Ecclesiastes',
    nameHebrew: 'קֹהֶלֶת',
    section: BibleSection.WRITINGS,
    chapterCount: 12,
    canonicalOrder: 30,
  },
  {
    morphhbKey: 'Lam',
    abbreviation: 'Lam',
    nameSpanish: 'Lamentaciones',
    nameEnglish: 'Lamentations',
    nameHebrew: 'אֵיכָה',
    section: BibleSection.WRITINGS,
    chapterCount: 5,
    canonicalOrder: 31,
  },
  {
    morphhbKey: 'Esth',
    abbreviation: 'Est',
    nameSpanish: 'Ester',
    nameEnglish: 'Esther',
    nameHebrew: 'אֶסְתֵּר',
    section: BibleSection.WRITINGS,
    chapterCount: 10,
    canonicalOrder: 32,
  },
  {
    morphhbKey: 'Dan',
    abbreviation: 'Dan',
    nameSpanish: 'Daniel',
    nameEnglish: 'Daniel',
    nameHebrew: 'דָּנִיֵּאל',
    section: BibleSection.WRITINGS,
    chapterCount: 12,
    canonicalOrder: 33,
  },
  {
    morphhbKey: 'Ezra',
    abbreviation: 'Esd',
    nameSpanish: 'Esdras',
    nameEnglish: 'Ezra',
    nameHebrew: 'עֶזְרָא',
    section: BibleSection.WRITINGS,
    chapterCount: 10,
    canonicalOrder: 34,
  },
  {
    morphhbKey: 'Neh',
    abbreviation: 'Neh',
    nameSpanish: 'Nehemías',
    nameEnglish: 'Nehemiah',
    nameHebrew: 'נְחֶמְיָה',
    section: BibleSection.WRITINGS,
    chapterCount: 13,
    canonicalOrder: 35,
  },
  {
    morphhbKey: '1Chr',
    abbreviation: '1Cr',
    nameSpanish: '1 Crónicas',
    nameEnglish: '1 Chronicles',
    nameHebrew: 'דִּבְרֵי הַיָּמִים א',
    section: BibleSection.WRITINGS,
    chapterCount: 29,
    canonicalOrder: 36,
  },
  {
    morphhbKey: '2Chr',
    abbreviation: '2Cr',
    nameSpanish: '2 Crónicas',
    nameEnglish: '2 Chronicles',
    nameHebrew: 'דִּבְרֵי הַיָּמִים ב',
    section: BibleSection.WRITINGS,
    chapterCount: 36,
    canonicalOrder: 37,
  },
  // ── Profetas menores que faltaban en la catálogo original ──────────
  // (v1.6: necesarios para que el asistente expositivo cubra el canon
  // OT completo cuando consume morphhb. Insertados al final con
  // canonicalOrder secuencial para no renumerar el resto.)
  {
    morphhbKey: 'Joel',
    abbreviation: 'Jl',
    nameSpanish: 'Joel',
    nameEnglish: 'Joel',
    nameHebrew: 'יוֹאֵל',
    section: BibleSection.LATTER_PROPHETS,
    chapterCount: 4,
    canonicalOrder: 38,
  },
  {
    morphhbKey: 'Obad',
    abbreviation: 'Abd',
    nameSpanish: 'Abdías',
    nameEnglish: 'Obadiah',
    nameHebrew: 'עֹבַדְיָה',
    section: BibleSection.LATTER_PROPHETS,
    chapterCount: 1,
    canonicalOrder: 39,
  },
];
