import type { BookRecommendations } from '../types';

/**
 * Curated bibliography for Génesis. Hero book #3 in the v1.7 launch
 * (the OT counterpart to Hebreos/Romanos) — chosen because:
 *   1. Most commonly preached OT book in expository series.
 *   2. Foundational for biblical theology (creation, fall, covenant,
 *      patriarchs).
 *   3. Has a remarkably full commentary tradition across every tier
 *      and tradition (evangelical, mainline, Jewish, German critical).
 *
 * Subsequent OT books are added per `recommendation_gap_no_suggestions`
 * telemetry — Salmos and Isaías are the natural next candidates.
 */
export const GENESIS_RECOMMENDATIONS: BookRecommendations = {
    bookId: 'GEN',
    bySourceType: {
        'commentary-critical': [
            {
                author: 'Wenham, Gordon J.',
                title: 'Genesis 1-15 / Genesis 16-50',
                series: 'WBC 1 & 2',
                publisher: 'Word',
                year: 1987,
                isbn: '9780849902000',
                tier: 'essential',
                languages: ['en'],
                rationale: '2 vols. Estándar técnico evangélico para Génesis. Atención detallada al hebreo y al género literario.',
            },
            {
                author: 'Westermann, Claus',
                title: 'Genesis 1-11 / Genesis 12-36 / Genesis 37-50',
                series: 'Continental Commentary',
                publisher: 'Fortress',
                year: 1994,
                isbn: '9780800695002',
                tier: 'essential',
                languages: ['en', 'de'],
                rationale: '3 vols. Comentario crítico-académico monumental con análisis tradicio-histórico exhaustivo.',
            },
            {
                author: 'Speiser, E. A.',
                title: 'Genesis: Introduction, Translation, and Notes',
                series: 'Anchor Yale Bible 1',
                publisher: 'Yale University Press',
                year: 1964,
                isbn: '9780300139938',
                tier: 'recommended',
                languages: ['en'],
                rationale: 'Clásico de la serie Anchor. Énfasis en paralelos antiguos del cercano oriente.',
            },
            {
                author: 'von Rad, Gerhard',
                title: 'Genesis: A Commentary',
                series: 'Old Testament Library (rev. ed.)',
                publisher: 'Westminster John Knox',
                year: 1972,
                isbn: '9780664209575',
                tier: 'essential',
                languages: ['en', 'de', 'es'],
                rationale: 'Comentario teológico clásico (escuela de Form Criticism). Ed. española por Sígueme.',
            },
        ],
        'commentary-expository': [
            {
                author: 'Hamilton, Victor P.',
                title: 'The Book of Genesis: Chapters 1-17 / Chapters 18-50',
                series: 'NICOT',
                publisher: 'Eerdmans',
                year: 1990,
                isbn: '9780802825216',
                tier: 'essential',
                languages: ['en'],
                rationale: '2 vols. Estándar evangélico contemporáneo. Equilibra rigor y aplicación pastoral.',
            },
            {
                author: 'Mathews, Kenneth A.',
                title: 'Genesis 1-11:26 / Genesis 11:27-50:26',
                series: 'New American Commentary 1A & 1B',
                publisher: 'Holman',
                year: 1996,
                isbn: '9780805401011',
                tier: 'recommended',
                languages: ['en', 'es'],
                rationale: '2 vols. Comentario expositivo evangélico de gran utilidad para predicación. Hay traducción parcial al español por Mundo Hispano.',
            },
            {
                author: 'Walton, John H.',
                title: 'Genesis',
                series: 'NIV Application Commentary',
                publisher: 'Zondervan Academic',
                year: 2001,
                isbn: '9780310206170',
                tier: 'recommended',
                languages: ['en'],
                rationale: 'Énfasis en cosmovisión antigua del cercano oriente y aplicación contemporánea. Particularmente fuerte en Génesis 1-11.',
            },
            {
                author: 'Waltke, Bruce K.; Fredricks, Cathi J.',
                title: 'Genesis: A Commentary',
                series: null,
                publisher: 'Zondervan Academic',
                year: 2001,
                isbn: '9780310224587',
                tier: 'recommended',
                languages: ['en'],
                rationale: 'Comentario expositivo desde tradición reformada. Fuerte en teología bíblica y conexión NT.',
            },
        ],
        'theological-monograph': [
            {
                author: 'Walton, John H.',
                title: 'The Lost World of Genesis One: Ancient Cosmology and the Origins Debate',
                series: null,
                publisher: 'IVP Academic',
                year: 2009,
                isbn: '9780830837045',
                tier: 'recommended',
                languages: ['en'],
                rationale: 'Lectura cosmológica funcional vs. material. Marco interpretativo crítico para Génesis 1.',
            },
            {
                author: 'Sailhamer, John H.',
                title: 'Genesis Unbound: A Provocative New Look at the Creation Account',
                series: null,
                publisher: 'Dawson Media',
                year: 1996,
                isbn: '9781576830673',
                tier: 'standard',
                languages: ['en'],
                rationale: 'Propuesta literaria-canónica para Génesis 1-11. Útil para diálogo con la cuestión histórico-científica.',
            },
            {
                author: 'Brueggemann, Walter',
                title: 'Genesis',
                series: 'Interpretation Commentary',
                publisher: 'Westminster John Knox',
                year: 1982,
                isbn: '9780804231015',
                tier: 'recommended',
                languages: ['en'],
                rationale: 'Lectura teológico-pastoral influyente, énfasis en pacto y promesa. Útil para predicación bíblica-teológica.',
            },
        ],
        'historical-background': [
            {
                author: 'Walton, John H.',
                title: 'Ancient Near Eastern Thought and the Old Testament: Introducing the Conceptual World of the Hebrew Bible',
                series: null,
                publisher: 'Baker Academic',
                year: 2018,
                isbn: '9780801049309',
                tier: 'essential',
                languages: ['en'],
                rationale: 'Marco general del trasfondo del cercano oriente antiguo aplicado al AT — particularmente fuerte para Génesis 1-11.',
            },
            {
                author: 'Hallo, William W.; Younger, K. Lawson (eds.)',
                title: 'The Context of Scripture: Canonical Compositions, Monumental Inscriptions, and Archival Documents from the Biblical World',
                series: 'COS',
                publisher: 'Brill',
                year: 1997,
                isbn: '9789004135666',
                tier: 'essential',
                languages: ['en'],
                rationale: '3 vols. Antología fundamental de textos del cercano oriente antiguo (Enuma Elish, Atrahasis, Gilgamesh). Esencial para Génesis 1-11.',
            },
        ],
        'primary-source-ancient': [
            {
                author: 'Pritchard, James B. (ed.)',
                title: 'Ancient Near Eastern Texts Relating to the Old Testament',
                series: 'ANET',
                publisher: 'Princeton University Press',
                year: 1969,
                isbn: '9780691035031',
                tier: 'essential',
                languages: ['en'],
                rationale: 'Antología clásica complementaria a COS. Mitos de creación, leyes de Hammurabi, anales reales.',
            },
            {
                author: 'Charlesworth, James H. (ed.)',
                title: 'The Old Testament Pseudepigrapha (vol. 2: Expansions of the OT)',
                series: 'OTP',
                publisher: 'Doubleday',
                year: 1985,
                isbn: '9780385188135',
                tier: 'recommended',
                languages: ['en'],
                rationale: 'Jubileos, 1 Enoc, Vida de Adán y Eva — tradiciones de recepción de Génesis en el judaísmo del Segundo Templo.',
            },
        ],
    },
};
