/**
 * getSyntacticMark
 *
 * Resolves the syntactic clause marker for a word, preferring the explicit
 * `clauseTag` generated by Gemini (new analyses) and falling back to
 * structural inference for legacy cached analyses.
 *
 * Priority:
 *  1. word.clauseTag            — explicit, authoritative (Gemini, new analyses)
 *  2. PREPOSITION category      — standalone prepositions (עַל, אֶל, מִן...)
 *  3. PREPOSITION_PREFIX role   — inseparable prefix prepositions (לְ, בְּ, כְּ, מִ)
 *     fused to a nominal; excluded when category=VERB because לְ + infinitive
 *     construct is a purpose/result marker, NOT a prepositional phrase
 *  4. CONSTRUCT state           — nominal in construct state (semikut)
 *  5. syntacticFn text          — text-based heuristic for apposition detection
 *
 * ⚠️  The structural fallback (steps 2-5) is a heuristic for legacy cached
 *     analyses that predate clauseTag. Re-analyzing a verse lets Gemini set
 *     clauseTag with full semantic context, which is always more accurate.
 */

import type { WordAnalysis } from '@dosfilos/domain';

export type SyntacticMark = 'PREP_PHRASE' | 'CONSTRUCT' | 'APPOSITION' | null;

export function getSyntacticMark(word: WordAnalysis): SyntacticMark {
  // 1. Explicit tag from Gemini — full semantic authority
  if (word.clauseTag === 'PREP_PHRASE') return 'PREP_PHRASE';
  if (word.clauseTag === 'CONSTRUCT')   return 'CONSTRUCT';
  if (word.clauseTag === 'APPOSITION')  return 'APPOSITION';

  const cat = word.category?.toUpperCase() ?? '';

  // 2. Standalone preposition (independent token, e.g. עַל, אֶל, מִן)
  if (cat === 'PREPOSITION') return 'PREP_PHRASE';

  // 3. Inseparable preposition prefix (לְ, בְּ, כְּ, מִ) fused to a nominal.
  //    IMPORTANT: Exclude VERB category — לְ + infinitive construct is a
  //    purpose/result clause marker (e.g. לְהַבִּיט = "to look toward"),
  //    NOT a prepositional phrase in Biblical Hebrew grammar.
  if (cat !== 'VERB') {
    const hasPrepositionPrefix = word.morphemes?.some(m => m.role === 'PREPOSITION_PREFIX') ?? false;
    if (hasPrepositionPrefix) return 'PREP_PHRASE';
  }

  // 4. Construct state (semikut) — nominal governing the following genitive
  if (word.nominalMorphology?.state === 'CONSTRUCT') return 'CONSTRUCT';

  // 5. Text heuristic for apposition (Spanish: "aposición")
  const fn = word.syntacticFunction?.toLowerCase() ?? '';
  if (fn.includes('aposic') || fn.includes('apósi')) return 'APPOSITION';

  return null;
}

/** Tailwind border-bottom classes for each syntactic mark */
export const SYNTACTIC_BORDER: Record<NonNullable<SyntacticMark>, string> = {
  PREP_PHRASE: 'border-b-2 border-cyan-500/70 hover:border-cyan-500 hover:bg-cyan-50/40 dark:hover:bg-cyan-950/20',
  CONSTRUCT:   'border-b-2 border-amber-500/70 hover:border-amber-500 hover:bg-amber-50/40 dark:hover:bg-amber-950/20',
  APPOSITION:  'border-b-2 border-violet-500/70 hover:border-violet-500 hover:bg-violet-50/40 dark:hover:bg-violet-950/20',
};

/** Dot color classes for syntactic pip indicator (coexists with verb underline) */
export const SYNTACTIC_DOT: Record<NonNullable<SyntacticMark>, string> = {
  PREP_PHRASE: 'bg-cyan-500',
  CONSTRUCT:   'bg-amber-500',
  APPOSITION:  'bg-violet-500',
};
