/**
 * getSyntacticMark
 *
 * Resolves the syntactic clause marker for a word, preferring the explicit
 * `clauseTag` generated by Gemini (new analyses) and falling back to
 * structural inference for legacy cached analyses.
 *
 * Priority:
 *  1. word.clauseTag   — explicit, authoritative (new analyses)
 *  2. PREPOSITION cat  — any preposition heads a prepositional phrase
 *  3. CONSTRUCT state  — any nominal in construct state (semikut)
 *  4. syntacticFn text — text-based heuristic for apposition detection
 */

import type { WordAnalysis } from '@dosfilos/domain';

export type SyntacticMark = 'PREP_PHRASE' | 'CONSTRUCT' | 'APPOSITION' | null;

export function getSyntacticMark(word: WordAnalysis): SyntacticMark {
  // 1. Explicit tag from Gemini (new analyses)
  if (word.clauseTag === 'PREP_PHRASE') return 'PREP_PHRASE';
  if (word.clauseTag === 'CONSTRUCT')   return 'CONSTRUCT';
  if (word.clauseTag === 'APPOSITION')  return 'APPOSITION';

  // 2. Structural fallback for legacy cached analyses
  const cat = word.category?.toUpperCase() ?? '';
  if (cat === 'PREPOSITION') return 'PREP_PHRASE';
  if (word.nominalMorphology?.state === 'CONSTRUCT') return 'CONSTRUCT';

  // 3. Text heuristic for apposition (Spanish: "aposición")
  const fn = word.syntacticFunction?.toLowerCase() ?? '';
  if (fn.includes('aposic') || fn.includes('apósi')) return 'APPOSITION';

  return null;
}

/** Tailwind border-bottom classes for each syntactic mark */
export const SYNTACTIC_BORDER: Record<NonNullable<SyntacticMark>, string> = {
  PREP_PHRASE: 'border-b-2 border-cyan-500/70 hover:border-cyan-500 hover:bg-cyan-50/40 dark:hover:bg-cyan-950/20',
  CONSTRUCT:   'border-b-2 border-amber-500/70 hover:border-amber-500 hover:bg-amber-50/40 dark:hover:bg-amber-950/20',
  APPOSITION:  'border-b-2 border-violet-500/70 hover:border-violet-500 hover:bg-violet-50/40 dark:hover:bg-violet-950/20',
};

/** Dot color classes for syntactic pip indicator (coexists with verb underline) */
export const SYNTACTIC_DOT: Record<NonNullable<SyntacticMark>, string> = {
  PREP_PHRASE: 'bg-cyan-500',
  CONSTRUCT:   'bg-amber-500',
  APPOSITION:  'bg-violet-500',
};
